// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:757551304535:web:6bc02f0ef8cee66a793812',
    messagingSenderId: '757551304535',
    projectId: 'talknow-b7b22',
    authDomain: 'talknow-b7b22.firebaseapp.com',
    storageBucket: 'talknow-b7b22.firebasestorage.app',
    measurementId: 'G-G9HNWMP1SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:757551304535:android:3167872a5292ae83793812',
    messagingSenderId: '757551304535',
    projectId: 'talknow-b7b22',
    storageBucket: 'talknow-b7b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:757551304535:ios:92377535edd933cf793812',
    messagingSenderId: '757551304535',
    projectId: 'talknow-b7b22',
    storageBucket: 'talknow-b7b22.firebasestorage.app',
    iosBundleId: 'com.example.shilpkar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:757551304535:ios:92377535edd933cf793812',
    messagingSenderId: '757551304535',
    projectId: 'talknow-b7b22',
    storageBucket: 'talknow-b7b22.firebasestorage.app',
    iosBundleId: 'com.example.shilpkar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:757551304535:web:d7d2f4eaa0f2db16793812',
    messagingSenderId: '757551304535',
    projectId: 'talknow-b7b22',
    authDomain: 'talknow-b7b22.firebaseapp.com',
    storageBucket: 'talknow-b7b22.firebasestorage.app',
    measurementId: 'G-NJ4XSNP0JX',
  );
}
